estimator:
  - name: discretizer
    params:
      bins_per_column:
        bmi: 2
      strategy: kmeans
  - name: standard-scaler
    params: {}
  - name: bagging
    params: {}


data:
  filepath: "./data/train_regression.csv"

metrics:
  - name: mean absolute error # same as above
    params: {}

export:
  output_dir: ./models

reports:
  dir: ./reports